---
networks:
- name: concourse
  type: manual
  subnets: (( param "Specify your concourse subnet" ))

jobs:
- name: web
  networks:
  - name: concourse
    static_ips: (( static_ips 0, 1, 2 ))
- name: haproxy
  networks:
  - name: concourse
    static_ips: (( static_ips 3, 4 ))
- name: worker
  networks:
  - name: concourse
- name: db
  networks:
  - name: concourse
