---
jobs:
  - name: haproxy
    instances: 1
    resource_pool: (( param "Define a resource pool for haproxy" ))
    networks:      (( param "Define the network that haproxy should run on" ))
    templates:
      - release: cf-haproxy
        name: haproxy

  - name: web
    instances: 1
    resource_pool: (( param "Define a resource pool for web" ))
    networks:      (( param "Define the network that web should run on" ))
    templates:
      - release: concourse
        name: tsa
      - release: concourse
        name: atc

  - name: db
    instances: 1
    resource_pool: (( param "Define a resource pool for the database" ))
    networks:      (( param "Define the network that the database should run on" ))
    persistent_disk: 10240
    templates:
      - release: concourse
        name: postgresql
      - release: shield
        name: shield-agent

  - name: worker
    instances: 3
    resource_pool: (( param "Define a resource pool for workers" ))
    networks:      (( param "Define the network that workers should run on" ))
    templates:
      - release: concourse
        name: groundcrew
      - release: concourse
        name: baggageclaim
      - release: garden-runc
        name: garden
