meta:
  authentication: (( param "Please specify an authentication parameters here (basic_auth_*/github_auth.*)" ))
  external_url: (( param "What is the external URL for this concourse?" ))
  ssl_pem: (( param "Want ssl? define a pem" ))
  shield_authorized_key: (( param "Specify the SSH public key from this environment's SHIELD daemon" 

jobs:
- name: haproxy
  templates:
    - name: haproxy
      properties:
        ha_proxy:
          backend_port: 8080
          backend_servers: (( grab jobs.web.networks.0.static_ips ))
          ssl_pem: (( grab meta.ssl_pem ))

- name: web
  templates:
    - name: tsa
      properties: {}
    - name: atc
      properties:
        bind_port: 8080
        publicly_viewable: true
        postgresql_database: atc
        .: (( inject meta.authentication ))
        external_url: (( grab meta.external_url ))

- name: db
  templates:
    - name: postgresql
      properties:
        databases:
          - name: atc
            role: atc
            password: (( vault meta.vault_prefix "/atcdb:password" ))


- name: worker
  templates:
    - name: baggageclaim
      properties: {}
    - name: garden
      properties:
        garden:
          listen_network: tcp
          listen_address: 0.0.0.0:7777
          enable_graph_cleanup: true

properties:
  shield:
    agent:
      daemon_public_key: (( grab meta.shield_authorized_key ))
